name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./kube-news/src
          file: ./kube-news/src/Dockerfile
          push: true
          tags: |
            gabrielbenicio/kube-news:${{ github.run_number }}
            gabrielbenicio/kube-news:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_SECRET_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws-region: us-east-1
      - name: Configurar Kubeconfig
        run:
      - name: Aplicar Deploy
        run:
      
  
