name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./kube-news/src
          file: ./kube-news/src/Dockerfile
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Auteticar na AWS
        run:
      - name: Configurar Kubeconfig
        run:
      - name: Aplicar Deploy
        run:
      
  
